>>>1. Cari keseluruhan ketetapan

SELECT COUNT(*), SUM(PBB_YG_HARUS_DIBAYAR_SPPT) FROM SPPT 
WHERE
THN_PAJAK_SPPT= '2015';

+ Hasilnya :
a). Seluruh ketetapan pada tahun pajak tersebut (V_KTP_ALL)
b). Seluruh tagihan pada tahun pajak tersebut (V_TGH_ALL)


>>>2. Cari transaksi/ketepan yang sudah bayar di pembayaran

SELECT COUNT(DISTINCT(KD_PROPINSI||KD_DATI2||KD_KECAMATAN||KD_KELURAHAN||KD_BLOK||NO_URUT||KD_JNS_OP)) AS TRANSAKSI, 
SUM(JML_SPPT_YG_DIBAYAR) AS PEMBAYARAN, SUM(DENDA_SPPT) AS DENDA, SUM(JML_SPPT_YG_DIBAYAR-DENDA_SPPT) AS KETETAPAN
FROM PEMBAYARAN_SPPT 
WHERE
EXTRACT(YEAR FROM TGL_PEMBAYARAN_SPPT) = '2015' AND
THN_PAJAK_SPPT= '2015';

+ Hasilnya : 
a). Transaksi/ketetapan yg sudah dibayarkan (V_KTP_LUNAS)
b). Jumlah pembayaran (V_BAYAR)
c). Jumlah denda (V_DENDA)
d). Jumlah ketetapan yang sudah dibayar, didapat dari V_BAYAR dikurangi V_DENDA --> (V_TGH_DIBAYAR)



>>>3. Mencari jumlah piutang/ketetapan yang belum dibayar

SELECT COUNT(DISTINCT(KD_PROPINSI||KD_DATI2||KD_KECAMATAN||KD_KELURAHAN||KD_BLOK||NO_URUT||KD_JNS_OP)), SUM(PBB_YG_HARUS_DIBAYAR_SPPT) 
FROM SPPT
WHERE
THN_PAJAK_SPPT = '2015' AND
KD_PROPINSI||KD_DATI2||KD_KECAMATAN||KD_KELURAHAN||KD_BLOK||NO_URUT||KD_JNS_OP
NOT IN (
SELECT DISTINCT(KD_PROPINSI||KD_DATI2||KD_KECAMATAN||KD_KELURAHAN||KD_BLOK||NO_URUT||KD_JNS_OP)
FROM PEMBAYARAN_SPPT 
WHERE
EXTRACT(YEAR FROM TGL_PEMBAYARAN_SPPT) = '2015' AND
THN_PAJAK_SPPT= '2015'
)

+ Hasilnya :
a). Seluruh ketetapan pada tahun pajak tersebut yang belum lunas (V_KTP_BLM_LUNAS)
b). Seluruh tagihan pada tahun pajak tersebut yang belum dibayar (V_TGH_BLM_DIBAYAR)

+ CATATAN: QUERY INI KETIKA DIJALANKAN BUTUH WAKTU YANG LAMA



>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> SUMMARY <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

V_KTP_ALL = V_KTP_LUNAS + V_KTP_BLM_LUNAS
V_TGH_ALL = V_TGH_DIBAYAR + V_TGH_BLM_DIBAYAR

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------------------------------------------------ CASE-CASE TERTENTU ---------------------------------------------------------------


>>>1. CASE Mencari kelebihan bayar

SELECT DISTINCT(A.KD_PROPINSI||A.KD_DATI2||A.KD_KECAMATAN||A.KD_KELURAHAN||A.KD_BLOK||A.NO_URUT||A.KD_JNS_OP) AS NOP,
(A.JML_SPPT_YG_DIBAYAR-A.DENDA_SPPT) AS PEMBAYARAN_KURANG_DENDA, B.PBB_YG_HARUS_DIBAYAR_SPPT  AS KETETAPAN_SPPT, 
((A.JML_SPPT_YG_DIBAYAR-A.DENDA_SPPT)- B.PBB_YG_HARUS_DIBAYAR_SPPT) AS SELISIH 
FROM PEMBAYARAN_SPPT A, SPPT B 
WHERE
A.KD_PROPINSI = B.KD_PROPINSI AND
A.KD_DATI2 = B.KD_DATI2 AND
A.KD_KECAMATAN = B.KD_KECAMATAN AND
A.KD_KELURAHAN = B.KD_KELURAHAN AND
A.KD_BLOK = B.KD_BLOK AND
A.NO_URUT = B.NO_URUT AND
A.KD_JNS_OP = B.KD_JNS_OP AND
A.THN_PAJAK_SPPT = B.THN_PAJAK_SPPT AND
(A.JML_SPPT_YG_DIBAYAR-A.DENDA_SPPT) > B.PBB_YG_HARUS_DIBAYAR_SPPT AND
EXTRACT(YEAR FROM A.TGL_PEMBAYARAN_SPPT) = '2015' AND
A.THN_PAJAK_SPPT= '2015'
ORDER BY A.KD_PROPINSI||A.KD_DATI2||A.KD_KECAMATAN||A.KD_KELURAHAN||A.KD_BLOK||A.NO_URUT||A.KD_JNS_OP ASC

+ Hasilnya : NOP, NILAI Ketetapan Pembayaran (Pembayaran - Dendan), NILAI Ketetapan SPPT, Selisih kelebihan (NILAI Ketetapan Pembayaran - NILAI Ketetapan SPPT)



>>>2. CASE Mencari SUSPECT kekurangan bayar

SELECT A.KD_PROPINSI||A.KD_DATI2||A.KD_KECAMATAN||A.KD_KELURAHAN||A.KD_BLOK||A.NO_URUT||A.KD_JNS_OP AS NOP,
(A.JML_SPPT_YG_DIBAYAR-A.DENDA_SPPT) AS PEMBAYARAN_KURANG_DENDA, B.PBB_YG_HARUS_DIBAYAR_SPPT  AS KETETAPAN_SPPT, 
(B.PBB_YG_HARUS_DIBAYAR_SPPT - (A.JML_SPPT_YG_DIBAYAR-A.DENDA_SPPT)) AS SELISIH 
FROM PEMBAYARAN_SPPT A, SPPT B 
WHERE
A.KD_PROPINSI = B.KD_PROPINSI AND
A.KD_DATI2 = B.KD_DATI2 AND
A.KD_KECAMATAN = B.KD_KECAMATAN AND
A.KD_KELURAHAN = B.KD_KELURAHAN AND
A.KD_BLOK = B.KD_BLOK AND
A.NO_URUT = B.NO_URUT AND
A.KD_JNS_OP = B.KD_JNS_OP AND
A.THN_PAJAK_SPPT = B.THN_PAJAK_SPPT AND
(A.JML_SPPT_YG_DIBAYAR-A.DENDA_SPPT) < B.PBB_YG_HARUS_DIBAYAR_SPPT AND
EXTRACT(YEAR FROM A.TGL_PEMBAYARAN_SPPT) = '2015' AND
A.THN_PAJAK_SPPT= '2015'
ORDER BY A.KD_PROPINSI||A.KD_DATI2||A.KD_KECAMATAN||A.KD_KELURAHAN||A.KD_BLOK||A.NO_URUT||A.KD_JNS_OP ASC

+ Hasilnya : NOP, NILAI Ketetapan Pembayaran (Pembayaran - Dendan), NILAI Ketetapan SPPT, Selisih kekurangan (NILAI Ketetapan SPPT - NILAI Ketetapan Pembayaran)

CATATAN: 
>> HASIL DARI QUERY INI HARUS DICEK LAGI, KARENA MEMUNGKINKAN SATU NOP BAYAR BERULANG KALI DENGAN NOMINAL YANG KURANG DARI NILAI
KETETAPAN SPPT (DICICIL) SAMPAI AKHIRNYA LUNAS.
>> GROUP SETIAP NOP YANG SAMA JUMLAHKAN NILAI KETETAPAN_PEMBAYARANNYA, JIKA SAMA DENGAN NILAI KETETAPAN_SPPT BERARTI NOP TERSEBUT SUDAH LUNAS, DAN
TIDAK TERMASUK PADA TRANSAKSI YANG KURANG BAYAR.



>>>3. CASE mencari NOP yang sudah bayar, tetapi status pembayaran di SPPT masih 0

SELECT KD_PROPINSI, KD_DATI2, KD_KECAMATAN, KD_KELURAHAN, KD_BLOK, NO_URUT, KD_JNS_OP, THN_PAJAK_SPPT
FROM PEMBAYARAN_SPPT
WHERE
THN_PAJAK_SPPT = '2009' AND
KD_PROPINSI||KD_DATI2||KD_KECAMATAN||KD_KELURAHAN||KD_BLOK||NO_URUT||KD_JNS_OP IN (
SELECT KD_PROPINSI||KD_DATI2||KD_KECAMATAN||KD_KELURAHAN||KD_BLOK||NO_URUT||KD_JNS_OP
FROM SPPT
WHERE 
KD_PROPINSI = '16' AND
KD_DATI2 = '09' AND
KD_KECAMATAN = '050' AND
THN_PAJAK_SPPT = '2009' AND
STATUS_PEMBAYARAN_SPPT = '0'
)

CATATAN: SESUAIKAN KODE-KODE DAN TAHUN PAJAK SESUAI DENGAN YANG DIINGINKAN.










------------- UPDATE QUERY KURANG BAYAR DENGAN KETENTUAN TGL BAYAR TERTENTU

SELECT A.KD_PROPINSI||A.KD_DATI2||A.KD_KECAMATAN||A.KD_KELURAHAN||A.KD_BLOK||A.NO_URUT||A.KD_JNS_OP AS NOP, 
B.NM_WP_SPPT,
B.PBB_YG_HARUS_DIBAYAR_SPPT  AS KETETAPAN_SPPT,
SUM((A.JML_SPPT_YG_DIBAYAR-A.DENDA_SPPT)) AS PEMBAYARAN, 
(B.PBB_YG_HARUS_DIBAYAR_SPPT - SUM((A.JML_SPPT_YG_DIBAYAR-A.DENDA_SPPT))) AS SELISIH,
C.NM_KELURAHAN 
FROM PEMBAYARAN_SPPT A, SPPT B, REF_KELURAHAN C 
WHERE
A.KD_PROPINSI = B.KD_PROPINSI AND
A.KD_DATI2 = B.KD_DATI2 AND
A.KD_KECAMATAN = B.KD_KECAMATAN AND
A.KD_KELURAHAN = B.KD_KELURAHAN AND
A.KD_BLOK = B.KD_BLOK AND
A.NO_URUT = B.NO_URUT AND
A.KD_JNS_OP = B.KD_JNS_OP AND
A.THN_PAJAK_SPPT = B.THN_PAJAK_SPPT AND
A.KD_PROPINSI = C.KD_PROPINSI AND
A.KD_DATI2 = C.KD_DATI2 AND
A.KD_KECAMATAN = C.KD_KECAMATAN AND
A.KD_KELURAHAN = C.KD_KELURAHAN AND
A.KD_KECAMATAN = '010' AND
EXTRACT(YEAR FROM A.TGL_PEMBAYARAN_SPPT) = '2015' AND
A.THN_PAJAK_SPPT= '2015'
GROUP BY A.KD_PROPINSI||A.KD_DATI2||A.KD_KECAMATAN||A.KD_KELURAHAN||A.KD_BLOK||A.NO_URUT||A.KD_JNS_OP, C.NM_KELURAHAN, 
B.NM_WP_SPPT, B.PBB_YG_HARUS_DIBAYAR_SPPT 
HAVING (B.PBB_YG_HARUS_DIBAYAR_SPPT - SUM((A.JML_SPPT_YG_DIBAYAR-A.DENDA_SPPT))) > 0 
ORDER BY A.KD_PROPINSI||A.KD_DATI2||A.KD_KECAMATAN||A.KD_KELURAHAN||A.KD_BLOK||A.NO_URUT||A.KD_JNS_OP ASC


>> HASL QUERY TIDAK ADA NOP YANG BERULANG, HASILNYA VALID



------------- UPDATE QUERY KURANG BAYAR DENGAN TIDAK ADA KETENTUAN TGL BAYAR TERTENTU

SELECT 
B.NM_WP_SPPT,
A.KD_PROPINSI||A.KD_DATI2||A.KD_KECAMATAN||A.KD_KELURAHAN||A.KD_BLOK||A.NO_URUT||A.KD_JNS_OP AS NOP, 
B.PBB_YG_HARUS_DIBAYAR_SPPT  AS KETETAPAN_SPPT,
SUM(A.JML_SPPT_YG_DIBAYAR)-SUM(A.DENDA_SPPT) AS SUDAH_BAYAR, 
(B.PBB_YG_HARUS_DIBAYAR_SPPT - SUM(A.JML_SPPT_YG_DIBAYAR)-SUM(A.DENDA_SPPT)) AS KURANG_BAYAR,
C.NM_KELURAHAN 
FROM PEMBAYARAN_SPPT A, SPPT B, REF_KELURAHAN C 
WHERE
A.KD_PROPINSI = B.KD_PROPINSI AND
A.KD_DATI2 = B.KD_DATI2 AND
A.KD_KECAMATAN = B.KD_KECAMATAN AND
A.KD_KELURAHAN = B.KD_KELURAHAN AND
A.KD_BLOK = B.KD_BLOK AND
A.NO_URUT = B.NO_URUT AND
A.KD_JNS_OP = B.KD_JNS_OP AND
A.THN_PAJAK_SPPT = B.THN_PAJAK_SPPT AND
A.KD_PROPINSI = C.KD_PROPINSI AND
A.KD_DATI2 = C.KD_DATI2 AND
A.KD_KECAMATAN = C.KD_KECAMATAN AND
A.KD_KELURAHAN = C.KD_KELURAHAN AND
A.KD_KECAMATAN = '061' AND
A.THN_PAJAK_SPPT= '2015'
GROUP BY A.KD_PROPINSI||A.KD_DATI2||A.KD_KECAMATAN||A.KD_KELURAHAN||A.KD_BLOK||A.NO_URUT||A.KD_JNS_OP, C.NM_KELURAHAN, 
B.NM_WP_SPPT, B.PBB_YG_HARUS_DIBAYAR_SPPT 
HAVING (B.PBB_YG_HARUS_DIBAYAR_SPPT - SUM((A.JML_SPPT_YG_DIBAYAR-A.DENDA_SPPT))) > 0 
ORDER BY A.KD_PROPINSI||A.KD_DATI2||A.KD_KECAMATAN||A.KD_KELURAHAN||A.KD_BLOK||A.NO_URUT||A.KD_JNS_OP ASC